name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Tests
        run: sbt +test

      - name: Coverage
        run: sbt clean coverage test coverageReport

      - name: Upload codecov
        uses: codecov/codecov-action@v2
