name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'



      - name: Tests
        run: sbt +test

      - name: Coverage
        run: sbt clean coverage test coverageReport

      - name: Upload codecov
        uses: codecov/codecov-action@v1
