name: labeler

on: [ pull_request ]

jobs:
  labeler:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: Label the PR action
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label the PR size
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '50'
          s_max_size: '150'
          m_max_size: '750'
          l_max_size: '1500'
          fail_if_xl: 'false'
          message_if_xl: 'This PR is so big! Please, split it 😊'
