name: scala-steward

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.PAT }}
          author-email: scala-steward@users.noreply.github.com
          author-name: Scala Steward
